// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkUserExistsByUsernameOrEmail = `-- name: CheckUserExistsByUsernameOrEmail :one
SELECT EXISTS(
        SELECT 1
        FROM users
        WHERE users.username = $1
    ) AS username_exists,
    EXISTS(
        SELECT 1
        FROM users
        WHERE users.email = $2
    ) AS email_exists
`

type CheckUserExistsByUsernameOrEmailParams struct {
	UsernameVal pgtype.Text
	EmailVal    string
}

type CheckUserExistsByUsernameOrEmailRow struct {
	UsernameExists bool
	EmailExists    bool
}

// Checks if a user exists with the given username or email.
// Returns a simple struct indicating existence for each.
func (q *Queries) CheckUserExistsByUsernameOrEmail(ctx context.Context, arg CheckUserExistsByUsernameOrEmailParams) (CheckUserExistsByUsernameOrEmailRow, error) {
	row := q.db.QueryRow(ctx, checkUserExistsByUsernameOrEmail, arg.UsernameVal, arg.EmailVal)
	var i CheckUserExistsByUsernameOrEmailRow
	err := row.Scan(&i.UsernameExists, &i.EmailExists)
	return i, err
}

const createOAuthAccount = `-- name: CreateOAuthAccount :one
INSERT INTO oauth_accounts (
    id,
    user_id,
    provider_id,
    provider_user_id,
    provider_username,
    provider_email,
    access_token,
    refresh_token,
    token_expires_at,
    raw_user_data
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, user_id, provider_id, provider_user_id, provider_username, provider_email, access_token, refresh_token, token_expires_at, raw_user_data, is_primary, created_at, updated_at
`

type CreateOAuthAccountParams struct {
	ID               string
	UserID           string
	ProviderID       string
	ProviderUserID   string
	ProviderUsername pgtype.Text
	ProviderEmail    pgtype.Text
	AccessToken      pgtype.Text
	RefreshToken     pgtype.Text
	TokenExpiresAt   pgtype.Timestamptz
	RawUserData      []byte
}

// Create a new oauth account for a user
func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, createOAuthAccount,
		arg.ID,
		arg.UserID,
		arg.ProviderID,
		arg.ProviderUserID,
		arg.ProviderUsername,
		arg.ProviderEmail,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
		arg.RawUserData,
	)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderID,
		&i.ProviderUserID,
		&i.ProviderUsername,
		&i.ProviderEmail,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.RawUserData,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (
    id,
    user_id,
    first_name,
    last_name,
    other_names,
    bio,
    phone
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, user_id, first_name, last_name, other_names, bio, phone, created_at, updated_at
`

type CreateProfileParams struct {
	ID         string
	UserID     string
	FirstName  string
	LastName   string
	OtherNames pgtype.Text
	Bio        pgtype.Text
	Phone      pgtype.Text
}

// Create a new profile for a user
func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.ID,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.OtherNames,
		arg.Bio,
		arg.Phone,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.OtherNames,
		&i.Bio,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    email,
    username,
    password_hash,
    is_active,
    is_verified,
    password_change_on_login,
    is_superuser
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    NOT $6::boolean,
    $7,
    $8
)
RETURNING id, email, username, password_hash, is_superuser, has_roles, is_active, is_verified, password_reset_requested, password_change_on_login, suspended_until, banned_at, deactivate_at, created_at, updated_at
`

type CreateUserParams struct {
	ID                    string
	Email                 string
	Username              pgtype.Text
	PasswordHash          pgtype.Text
	IsActive              bool
	RequiresVerification  bool
	PasswordChangeOnLogin bool
	IsSuperuser           bool
}

// Create a new user
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.IsActive,
		arg.RequiresVerification,
		arg.PasswordChangeOnLogin,
		arg.IsSuperuser,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.IsSuperuser,
		&i.HasRoles,
		&i.IsActive,
		&i.IsVerified,
		&i.PasswordResetRequested,
		&i.PasswordChangeOnLogin,
		&i.SuspendedUntil,
		&i.BannedAt,
		&i.DeactivateAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByUserID = `-- name: GetAccountByUserID :one
SELECT
    u.id,
    u.email,
    u.username,
    u.password_hash,
    u.is_superuser,
    u.has_roles,
    u.is_active,
    u.is_verified,
    u.password_reset_requested,
    u.password_change_on_login,
    u.suspended_until,
    u.banned_at,
    u.deactivate_at,
    u.created_at,
    u.updated_at,
    p.id as profile_id,
    p.user_id,
    p.first_name,
    p.last_name,
    p.other_names,
    p.bio,
    p.phone,
    p.created_at as profile_created_at,
    p.updated_at as profile_updated_at
FROM users AS u
INNER JOIN profiles AS p
ON u.id = p.user_id
WHERE
    u.id = $1
`

type GetAccountByUserIDRow struct {
	ID                     string
	Email                  string
	Username               pgtype.Text
	PasswordHash           pgtype.Text
	IsSuperuser            bool
	HasRoles               bool
	IsActive               bool
	IsVerified             bool
	PasswordResetRequested bool
	PasswordChangeOnLogin  bool
	SuspendedUntil         pgtype.Timestamptz
	BannedAt               pgtype.Timestamptz
	DeactivateAt           pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	ProfileID              string
	UserID                 string
	FirstName              string
	LastName               string
	OtherNames             pgtype.Text
	Bio                    pgtype.Text
	Phone                  pgtype.Text
	ProfileCreatedAt       pgtype.Timestamptz
	ProfileUpdatedAt       pgtype.Timestamptz
}

// Retrieves the full account by ID
func (q *Queries) GetAccountByUserID(ctx context.Context, userID string) (GetAccountByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getAccountByUserID, userID)
	var i GetAccountByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.IsSuperuser,
		&i.HasRoles,
		&i.IsActive,
		&i.IsVerified,
		&i.PasswordResetRequested,
		&i.PasswordChangeOnLogin,
		&i.SuspendedUntil,
		&i.BannedAt,
		&i.DeactivateAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.OtherNames,
		&i.Bio,
		&i.Phone,
		&i.ProfileCreatedAt,
		&i.ProfileUpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, password_hash, is_superuser, has_roles, is_active, is_verified, password_reset_requested, password_change_on_login, suspended_until, banned_at, deactivate_at, created_at, updated_at FROM users WHERE email = $1 LIMIT 1
`

// Retrieves a user by their email.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.IsSuperuser,
		&i.HasRoles,
		&i.IsActive,
		&i.IsVerified,
		&i.PasswordResetRequested,
		&i.PasswordChangeOnLogin,
		&i.SuspendedUntil,
		&i.BannedAt,
		&i.DeactivateAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, password_hash, is_superuser, has_roles, is_active, is_verified, password_reset_requested, password_change_on_login, suspended_until, banned_at, deactivate_at, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

// Retrieves a user by the ID
func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.IsSuperuser,
		&i.HasRoles,
		&i.IsActive,
		&i.IsVerified,
		&i.PasswordResetRequested,
		&i.PasswordChangeOnLogin,
		&i.SuspendedUntil,
		&i.BannedAt,
		&i.DeactivateAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetPassword = `-- name: ResetPassword :exec
UPDATE users
SET
    password_hash = $1,
    password_reset_requested = false
WHERE
    id = $2
`

type ResetPasswordParams struct {
	PasswordHash pgtype.Text
	ID           string
}

// Reset's an account's password
func (q *Queries) ResetPassword(ctx context.Context, arg ResetPasswordParams) error {
	_, err := q.db.Exec(ctx, resetPassword, arg.PasswordHash, arg.ID)
	return err
}

const setPasswordResetFlag = `-- name: SetPasswordResetFlag :exec
UPDATE users
SET password_reset_requested = true
WHERE email = $1
`

// Sets the password reset flag on an account
func (q *Queries) SetPasswordResetFlag(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, setPasswordResetFlag, email)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password_hash = $1
WHERE id = $2
`

type UpdatePasswordParams struct {
	PasswordHash pgtype.Text
	ID           string
}

// Updates a user's password hash
func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.PasswordHash, arg.ID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE profiles
SET 
    first_name = COALESCE($1, first_name),
    last_name = COALESCE($2, last_name),
    other_names = COALESCE($3, other_names),
    phone = COALESCE($4, phone),
    bio = COALESCE($5, bio)
WHERE user_id = $6
RETURNING id, user_id, first_name, last_name, other_names, bio, phone, created_at, updated_at
`

type UpdateUserProfileParams struct {
	FirstName  pgtype.Text
	LastName   pgtype.Text
	OtherNames pgtype.Text
	Phone      pgtype.Text
	Bio        pgtype.Text
	UserID     string
}

// Updates a user's profile information.
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.FirstName,
		arg.LastName,
		arg.OtherNames,
		arg.Phone,
		arg.Bio,
		arg.UserID,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.OtherNames,
		&i.Bio,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyUserAccount = `-- name: VerifyUserAccount :exec
UPDATE users
SET 
    is_verified = TRUE
WHERE id = $1
`

// Marks a user's account as verified.
func (q *Queries) VerifyUserAccount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, verifyUserAccount, id)
	return err
}
