// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthAccount = `-- name: CreateOAuthAccount :one
INSERT INTO oauth_accounts (
    id,
    user_id,
    provider_id,
    provider_user_id,
    provider_username,
    provider_email,
    access_token,
    refresh_token,
    token_expires_at,
    raw_user_data
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, user_id, provider_id, provider_user_id, provider_username, provider_email, access_token, refresh_token, token_expires_at, raw_user_data, is_primary, created_at, updated_at
`

type CreateOAuthAccountParams struct {
	ID               string
	UserID           string
	ProviderID       string
	ProviderUserID   string
	ProviderUsername pgtype.Text
	ProviderEmail    pgtype.Text
	AccessToken      pgtype.Text
	RefreshToken     pgtype.Text
	TokenExpiresAt   pgtype.Timestamptz
	RawUserData      []byte
}

// Create a new oauth account for a user
func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, createOAuthAccount,
		arg.ID,
		arg.UserID,
		arg.ProviderID,
		arg.ProviderUserID,
		arg.ProviderUsername,
		arg.ProviderEmail,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
		arg.RawUserData,
	)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderID,
		&i.ProviderUserID,
		&i.ProviderUsername,
		&i.ProviderEmail,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.RawUserData,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (
    id,
    user_id,
    first_name,
    last_name,
    other_names,
    bio,
    phone
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, user_id, first_name, last_name, other_names, bio, phone, created_at, updated_at
`

type CreateProfileParams struct {
	ID         string
	UserID     string
	FirstName  string
	LastName   string
	OtherNames pgtype.Text
	Bio        pgtype.Text
	Phone      pgtype.Text
}

// Create a new profile for a user
func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.ID,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.OtherNames,
		arg.Bio,
		arg.Phone,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.OtherNames,
		&i.Bio,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    email,
    username,
    password_hash,
    is_verified
) VALUES (
    $1,
    $2,
    $3,
    $4,
    NOT $5::boolean
)
RETURNING id, email, username, password_hash, is_superuser, has_roles, is_active, is_verified, password_reset_requested, password_change_on_login, suspended_until, banned_at, deactivate_at, created_at, updated_at
`

type CreateUserParams struct {
	ID                   string
	Email                string
	Username             pgtype.Text
	PasswordHash         pgtype.Text
	RequiresVerification bool
}

// Create a new user
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.RequiresVerification,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.IsSuperuser,
		&i.HasRoles,
		&i.IsActive,
		&i.IsVerified,
		&i.PasswordResetRequested,
		&i.PasswordChangeOnLogin,
		&i.SuspendedUntil,
		&i.BannedAt,
		&i.DeactivateAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
