// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: analytics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (id, name, description)
VALUES ($1, $2, $3)
RETURNING id, name, description, created_at, updated_at
`

type CreateEventParams struct {
	ID          string
	Name        string
	Description pgtype.Text
}

// Creates an event
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent, arg.ID, arg.Name, arg.Description)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordMetric = `-- name: RecordMetric :exec
INSERT INTO metrics (
    id,
    event_id,
    dimensions,
    "date",
    "count"
) VALUES (
    $1,
    $2,
    $3::date,
    $4::jsonb,
    $5
)
`

type RecordMetricParams struct {
	ID         string
	EventID    string
	Date       pgtype.Date
	Dimensions []byte
	Count      int64
}

// Records a metric
func (q *Queries) RecordMetric(ctx context.Context, arg RecordMetricParams) error {
	_, err := q.db.Exec(ctx, recordMetric,
		arg.ID,
		arg.EventID,
		arg.Date,
		arg.Dimensions,
		arg.Count,
	)
	return err
}
