// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Effect string

const (
	EffectAllow Effect = "allow"
	EffectDeny  Effect = "deny"
)

func (e *Effect) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Effect(s)
	case string:
		*e = Effect(s)
	default:
		return fmt.Errorf("unsupported scan type for Effect: %T", src)
	}
	return nil
}

type NullEffect struct {
	Effect Effect
	Valid  bool // Valid is true if Effect is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEffect) Scan(value interface{}) error {
	if value == nil {
		ns.Effect, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Effect.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEffect) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Effect), nil
}

type Action struct {
	ID          string
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type AuditLog struct {
	ID            string
	UserID        pgtype.Text
	SessionID     pgtype.Text
	Action        string
	ResourceType  pgtype.Text
	ResourceID    pgtype.Text
	PreviousState []byte
	UpdatedState  []byte
	IpAddress     *netip.Addr
	UserAgent     pgtype.Text
	RequestID     pgtype.Text
	Success       bool
	ErrorCode     pgtype.Text
	ErrorMessage  pgtype.Text
	Metadata      []byte
	CreatedAt     pgtype.Timestamptz
}

type OauthAccount struct {
	ID               string
	UserID           string
	ProviderID       string
	ProviderUserID   string
	ProviderUsername pgtype.Text
	ProviderEmail    pgtype.Text
	AccessToken      pgtype.Text
	RefreshToken     pgtype.Text
	TokenExpiresAt   pgtype.Timestamptz
	RawUserData      []byte
	IsPrimary        bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type OauthProvider struct {
	ID          string
	Name        string
	AuthUrl     string
	TokenUrl    string
	UserInfoUrl string
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Permission struct {
	ID          string
	Name        string
	Description pgtype.Text
	ActionID    string
	ResourceID  string
	ScopeID     pgtype.Text
	Effect      Effect
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Profile struct {
	ID         string
	UserID     string
	FirstName  string
	LastName   string
	OtherNames pgtype.Text
	Bio        pgtype.Text
	Phone      pgtype.Text
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Resource struct {
	ID          string
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Role struct {
	ID          string
	Name        string
	Description pgtype.Text
}

type RolesPermission struct {
	ID           string
	RoleID       string
	PermissionID string
	AssignedAt   pgtype.Timestamptz
	AssignedBy   pgtype.Text
}

type RolesUser struct {
	ID         string
	RoleID     string
	UserID     string
	AssignedAt pgtype.Timestamptz
}

type Scope struct {
	ID          string
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	ID                     string
	Email                  string
	Username               pgtype.Text
	PasswordHash           pgtype.Text
	IsSuperuser            bool
	HasRoles               bool
	IsActive               bool
	IsVerified             bool
	PasswordResetRequested bool
	PasswordChangeOnLogin  bool
	SuspendedUntil         pgtype.Timestamptz
	BannedAt               pgtype.Timestamptz
	DeactivateAt           pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type UsersPermission struct {
	ID           string
	UserID       string
	PermissionID string
	AssignedAt   pgtype.Timestamptz
	AssignedBy   pgtype.Text
}
